#!/usr/bin/env python3
"""Send generated reports via Resend API"""

import os
import json
from pathlib import Path
from datetime import date
import urllib.request
import urllib.error

def send_reports():
    # Find reports generated today
    today = date.today().isoformat()
    report_dir = Path('logs')

    print(f"Looking for reports generated on: {today}")

    report_types = ['daily', 'weekly', 'biweekly', 'monthly']
    generated_reports = {}

    for report_type in report_types:
        pattern = f'unified_master_report_{today}_*{report_type}*.txt'
        matches = list(report_dir.glob(pattern))
        if matches:
            generated_reports[report_type] = matches[0]
            print(f"  Found {report_type}: {matches[0].name}")

    if not generated_reports:
        print("No new reports generated today")
        return

    # Get API key
    api_key = os.getenv('RESEND_API_KEY')
    if not api_key:
        print("ERROR: RESEND_API_KEY not set")
        return

    # Icons for subject lines
    icons = {
        'daily': '📊',
        'weekly': '📈',
        'biweekly': '🔄',
        'monthly': '📅'
    }

    # Send each report
    for report_type, report_file in generated_reports.items():
        try:
            report_text = report_file.read_text()
            icon = icons.get(report_type, '📊')

            # Create HTML email body
            html_body = create_html_body(report_type, report_text)

            # Create payload
            subject = f"{icon} {report_type.upper()} — Unified Master Report ({today})"
            payload = {
                'from': 'noreply@resend.dev',
                'to': 'ravjdpr@gmail.com',
                'subject': subject,
                'html': html_body
            }

            # Send via Resend API
            send_email(api_key, payload)
            print(f"✅ {report_type.upper()} report sent")

        except Exception as e:
            print(f"❌ {report_type.upper()} email failed: {e}")


def create_html_body(report_type, report_text):
    """Create HTML email body for a report"""
    css = """
        body {
            font-family: Arial, sans-serif;
            max-width: 1000px;
            margin: 0 auto;
            color: #222;
            background: #fff;
        }
        .header {
            background: #1a3a52;
            color: white;
            padding: 20px 24px;
            border-radius: 6px 6px 0 0;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header .subtitle {
            font-size: 12px;
            color: #aaa;
            margin-top: 6px;
        }
        .content {
            padding: 20px 24px;
            font-family: 'Courier New', monospace;
            font-size: 11px;
            white-space: pre-wrap;
            line-height: 1.5;
            background: #f5f5f5;
            border: 1px solid #ddd;
            max-height: 800px;
            overflow-y: auto;
        }
        .footer {
            padding: 12px 16px;
            font-size: 10px;
            color: #888;
            border-top: 1px solid #ddd;
            text-align: center;
            background: #fafafa;
        }
        .report-type {
            text-transform: uppercase;
            letter-spacing: 1px;
            font-size: 13px;
        }
    """

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>{css}</style>
</head>
<body>
    <div class="header">
        <h1><span class="report-type">{report_type}</span> Report</h1>
        <div class="subtitle">Theta-Lab Unified Master Reports</div>
    </div>
    <div class="content">{report_text}</div>
    <div class="footer">Automated report generated by Theta-Lab scheduler</div>
</body>
</html>"""


def send_email(api_key, payload):
    """Send email via Resend API"""
    payload_json = json.dumps(payload).encode('utf-8')

    req = urllib.request.Request(
        'https://api.resend.com/emails',
        data=payload_json,
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}'
        },
        method='POST'
    )

    with urllib.request.urlopen(req) as response:
        result = json.loads(response.read())
        return result


if __name__ == '__main__':
    send_reports()
